services:
  # ===================
  # バックエンド (Flask)
  # ===================
  - type: web
    name: book-order-backend
    env: python
    region: oregon # リージョンはご自身のものに合わせてください
    plan: free
    # backendディレクトリに移動してからビルドコマンドを実行
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    # waitressをWSGIサーバーとして使用
    startCommand: "waitress-serve --host=0.0.0.0 --port=$PORT app:app"
    healthCheckPath: /api/health # ヘルスチェック用のパスを指定
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # Pythonのバージョンを明示的に指定
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      # --- Renderのダッシュボードからコピー ---
      - key: SECRET_KEY
        sync: false # ダッシュボードの値を優先
      - key: DATABASE_URL
        sync: false # ダッシュボードの値を優先
      - key: ADMIN_USERNAME
        sync: false # ダッシュボードの値を優先
      - key: ADMIN_PASSWORD
        sync: false # ダッシュボードの値を優先
      - key: GOOGLE_BOOKS_API_KEY
        sync: false # ダッシュボードの値を優先

  # =================================
  # フロントエンド (React - 静的サイト)
  # =================================
  - type: web
    name: book-order-frontend
    env: static
    # frontendディレクトリに移動してからビルドコマンドを実行
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://book-order-backend-6uzl.onrender.com" # バックエンドのURL
